// C mirror of software/esw/if4.py::verify() -- see if4_verify.h.
// Proven against the Python reference on every boot via test_vectors.h
// (generated by tools/gen_vectors.py from the real esw.if4.encode_show).
#include "if4_verify.h"

// Constant-time tag compare -- mirror of esw/crypto.py::ct_equal. No early exit:
// a byte-by-byte break would leak how many tag bytes matched (a timing oracle
// an RF attacker could farm at 2 frames/s).
static bool ct_equal(const uint8_t *a, const uint8_t *b, size_t n) {
    uint8_t diff = 0;
    for (size_t i = 0; i < n; i++) {
        diff |= (uint8_t)(a[i] ^ b[i]);
    }
    return diff == 0;
}

static uint32_t be32(const uint8_t *p) {
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) |
           ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static int64_t be48(const uint8_t *p) {
    uint64_t v = 0;
    for (int i = 0; i < 6; i++) {
        v = (v << 8) | p[i];
    }
    return (int64_t)v;   // 48-bit ms fits int64 for ~8900 years
}

if4_verdict_t if4_verify(const uint8_t *key, size_t key_len,
                         const uint8_t *frame, size_t frame_len,
                         bool have_last_seq, uint32_t last_seq,
                         int64_t now_ms, int64_t replay_window_ms) {
    // All reject paths return {reason, 0, 0}, matching Python's _bad().
    if4_verdict_t v = { IF4_REJ_LEN, 0, 0 };
    if (frame == NULL || frame_len != IF4_FRAME_LEN) {
        return v;
    }
    if (frame[0] != IF4_VERSION || frame[1] != IF4_MSG_SHOW) {
        v.result = IF4_REJ_PROTO;
        return v;
    }
    uint8_t want[32];
    if4_hmac_sha256(key, key_len, frame, IF4_HEADER_LEN, want);
    if (!ct_equal(frame + IF4_HEADER_LEN, want, IF4_TAG_LEN)) {
        v.result = IF4_REJ_AUTH;
        return v;
    }
    uint32_t seq = be32(frame + 3);
    if (have_last_seq && seq <= last_seq) {
        v.result = IF4_REJ_REPLAY;
        return v;
    }
    int64_t ts = be48(frame + 15);
    int64_t d = now_ms - ts;
    if (d < 0) {
        d = -d;
    }
    if (d > replay_window_ms) {
        v.result = IF4_REJ_STALE;
        return v;
    }
    v.result = IF4_OK;
    v.message_id = frame[2];
    v.seq = seq;
    return v;
}

const char *if4_reason(if4_result_t r) {
    switch (r) {
        case IF4_OK:         return "ok";
        case IF4_REJ_LEN:    return "len";
        case IF4_REJ_PROTO:  return "proto";
        case IF4_REJ_AUTH:   return "auth";
        case IF4_REJ_REPLAY: return "replay";
        case IF4_REJ_STALE:  return "stale";
    }
    return "?";
}
